name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        run: | 
          wget -O hugo.deb $(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep -oP '"browser_download_url": "\K(.*)hugo(.*)Linux-64bit.deb')
          sudo dpkg -i hugo.deb
          rm hugo.deb   
          
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: Install node packages  
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Deploy
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-av --delete-before"
          SERVER_PORT: ${{ secrets.PORT }}
          FOLDER: "./public/"
          SERVER_IP: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_DESTINATION: "./www/ppnp.me/"
